name: Draw ZMK keymaps
on:
  workflow_dispatch:

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    permissions:
      contents: write
    with:
      keymap_patterns: "config/totem.keymap"
      config_path: 'keymap_drawer.config.yaml'
      destination: ${{ inputs.destination }}
      west_config_path: './config/'
      # install repo and branch can be removed once https://github.com/caksoylar/keymap-drawer/pull/105 has been merged
      install_repo: 'https://github.com/stijnveenman/keymap-drawer.git'
      install_branch: 'feature/additional_includes'
